import type { ServiceDefinition } from '../core';

/**
 * Templates for the files the CLI writes into a consumer's project.
 *
 * These are generated from the registry rather than hand-maintained. The 1.x
 * templates held a second, hand-authored copy of every service and every SVG,
 * which drifted from the real catalogue and eventually shipped corrupted — a
 * truncated path had swallowed the start of a second `services` record, so the
 * `core.tsx` the CLI wrote did not compile at all. Deriving the text from the
 * same data the library uses makes that class of bug impossible.
 */

const BANNER = `/**
 * Generated by @raptrx/askai. You own this file — edit it freely.
 *
 * Deep-link parameters are not a public API for any of these vendors and do
 * change. Each entry below records when it was last verified. If a destination
 * stops working, check the parameter before assuming the code is wrong.
 */`;

function literal(value: string): string {
  return JSON.stringify(value);
}

function renderService(s: ServiceDefinition): string {
  const extra = s.extraParams
    ? `\n    extraParams: ${JSON.stringify(s.extraParams)},`
    : '';
  const note = s.note ? `\n    // ${s.note.replace(/\s+/g, ' ')}` : '';
  return `  ${JSON.stringify(s.id)}: {${note}
    name: ${literal(s.name)},
    url: ${literal(s.url)},
    param: ${literal(s.param)},${extra}
    maxLength: ${s.maxLength},
    autoSubmit: ${s.autoSubmit},
    color: ${literal(s.color)},
    verifiedOn: ${literal(s.verifiedOn)},
  },`;
}

/** The prompt-building core, with only the services the user selected. */
export function renderCore(services: ServiceDefinition[]): string {
  const ids = services.map((s) => JSON.stringify(s.id)).join(' | ');

  return `${BANNER}

export type ServiceId = ${ids};

export interface AiService {
  name: string;
  url: string;
  param: string;
  extraParams?: Record<string, string>;
  /** Maximum characters this destination accepts in the URL. */
  maxLength: number;
  /** Whether it runs the prompt on arrival, or just fills the composer. */
  autoSubmit: boolean;
  color: string;
  verifiedOn: string;
}

export const services: Record<ServiceId, AiService> = {
${services.map(renderService).join('\n')}
};

export interface PromptResult {
  service: ServiceId;
  name: string;
  url: string;
  autoSubmit: boolean;
  truncated: boolean;
  droppedChars: number;
}

function looksLikeCode(text: string): boolean {
  return [
    /^\\s*(import|export|const|let|var|function|class|interface|type|def|from)\\s/m,
    /[)\\]}]\\s*=>/,
    /\\{\\s*$/m,
    /<\\/?[A-Za-z][A-Za-z0-9-]*(\\s[^<>]*)?\\/?>/,
  ].some((re) => re.test(text));
}

function fence(text: string, language = ''): string {
  const longest = (text.match(/\`+/g) || []).reduce(
    (n, m) => Math.max(n, m.length),
    0
  );
  const bar = '\`'.repeat(Math.max(3, longest + 1));
  return bar + language + '\\n' + text + '\\n' + bar;
}

/**
 * Build the deep link for one destination.
 *
 * Content longer than the destination accepts is truncated and reported, never
 * silently cut — an AI answering confidently about half a function is worse
 * than no answer.
 */
export function buildPrompt(
  service: ServiceId,
  goal: string,
  content: string,
  language?: string
): PromptResult {
  const config = services[service];
  if (!config) throw new Error('Unknown AI service: ' + service);

  const isCode = Boolean(language) || looksLikeCode(content);
  const wrap = (body: string) =>
    goal + '\\n\\n' + (isCode ? fence(body, language || '') : body);

  const full = wrap(content);
  let body = content;
  let truncated = false;
  let droppedChars = 0;

  if (full.length > config.maxLength) {
    const overhead = full.length - content.length;
    const budget = Math.max(0, config.maxLength - overhead - 1);
    body = content.slice(0, budget) + '\\u2026';
    droppedChars = content.length - budget;
    truncated = true;
  }

  const url = new URL(config.url);
  for (const [k, v] of Object.entries(config.extraParams || {})) {
    url.searchParams.set(k, v);
  }
  url.searchParams.set(config.param, wrap(body));

  return {
    service,
    name: config.name,
    url: url.toString(),
    autoSubmit: config.autoSubmit,
    truncated,
    droppedChars,
  };
}

export function buildPromptUrl(
  service: ServiceId,
  goal: string,
  content: string
): string {
  return buildPrompt(service, goal, content).url;
}

/**
 * Prefer rendering an anchor. This exists for imperative call sites; a real
 * link supports middle-click, Cmd-click and "copy link address".
 */
export function openInAI(
  service: ServiceId,
  goal: string,
  content: string
): void {
  window.open(buildPromptUrl(service, goal, content), '_blank', 'noopener,noreferrer');
}

export function getAllServices(): ServiceId[] {
  return Object.keys(services) as ServiceId[];
}
`;
}

/** A single-destination anchor. */
export function renderLink(defaultService: string, defaultGoal: string): string {
  return `${BANNER}

import * as React from 'react';
import { buildPrompt, services, type ServiceId } from './core';

export interface AskAiLinkProps
  extends Omit<React.AnchorHTMLAttributes<HTMLAnchorElement>, 'href' | 'content'> {
  service?: ServiceId;
  goal?: string;
  content: string;
  language?: string;
}

export const DEFAULT_SERVICE: ServiceId = ${literal(defaultService)};
export const DEFAULT_GOAL = ${literal(defaultGoal)};

/**
 * Renders a real link, so middle-click and Cmd-click behave and the markup
 * needs no client boundary.
 */
export const AskAiLink = React.forwardRef<HTMLAnchorElement, AskAiLinkProps>(
  function AskAiLink(
    {
      service = DEFAULT_SERVICE,
      goal = DEFAULT_GOAL,
      content,
      language,
      children,
      ...rest
    },
    ref
  ) {
    const result = buildPrompt(service, goal, content, language);
    return (
      <a
        ref={ref}
        href={result.url}
        target="_blank"
        rel="noopener noreferrer"
        {...rest}
      >
        {children || 'Ask ' + result.name}
      </a>
    );
  }
);
`;
}

/** The split button: copy the prompt, or pick a destination. */
export function renderButton(defaultServices: string[], defaultGoal: string): string {
  return `'use client';

${BANNER}

import * as React from 'react';
import { buildPrompt, services, type ServiceId, type PromptResult } from './core';

export interface AskAiButtonProps {
  goal?: string;
  content: string;
  language?: string;
  services?: ServiceId[];
  label?: string;
  className?: string;
  onCopy?: (prompt: string) => void;
  onOpen?: (result: PromptResult) => void;
}

export const DEFAULT_GOAL = ${literal(defaultGoal)};
export const DEFAULT_SERVICES: ServiceId[] = ${JSON.stringify(defaultServices)};

/**
 * Copy is the primary action because it has no length ceiling: the deep links
 * below are bounded by each destination's URL limit, copying is not.
 */
export const AskAiButton: React.FC<AskAiButtonProps> = ({
  goal = DEFAULT_GOAL,
  content,
  language,
  services: selected = DEFAULT_SERVICES,
  label = 'Copy prompt',
  className,
  onCopy,
  onOpen,
}) => {
  const [open, setOpen] = React.useState(false);
  const [copied, setCopied] = React.useState(false);
  const rootRef = React.useRef<HTMLDivElement>(null);
  const triggerRef = React.useRef<HTMLButtonElement>(null);

  const results = React.useMemo(
    () => selected.map((id) => buildPrompt(id, goal, content, language)),
    [selected, goal, content, language]
  );

  const prompt = React.useMemo(() => {
    const longest = results.reduce(
      (a, b) => (b.url.length > a.url.length ? b : a),
      results[0]
    );
    return new URL(longest.url).searchParams.get(services[longest.service].param) || '';
  }, [results]);

  React.useEffect(() => {
    if (!copied) return;
    const t = setTimeout(() => setCopied(false), 2000);
    return () => clearTimeout(t);
  }, [copied]);

  React.useEffect(() => {
    if (!open) return;
    const onDown = (e: PointerEvent) => {
      if (!rootRef.current?.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener('pointerdown', onDown);
    return () => document.removeEventListener('pointerdown', onDown);
  }, [open]);

  return (
    <div ref={rootRef} className={className} style={{ position: 'relative', display: 'inline-flex' }}>
      <button
        type="button"
        onClick={async () => {
          await navigator.clipboard.writeText(prompt);
          setCopied(true);
          onCopy?.(prompt);
        }}
      >
        {copied ? 'Copied' : label}
      </button>

      <button
        ref={triggerRef}
        type="button"
        aria-haspopup="menu"
        aria-expanded={open}
        aria-label="Send to an AI assistant"
        onClick={() => setOpen((v) => !v)}
      >
        {'\\u25BE'}
      </button>

      {open && (
        <ul
          role="menu"
          style={{ position: 'absolute', top: '100%', right: 0, zIndex: 50, listStyle: 'none', margin: 0, padding: 4 }}
          onKeyDown={(e) => {
            if (e.key === 'Escape') {
              setOpen(false);
              triggerRef.current?.focus();
            }
          }}
        >
          {results.map((result) => (
            <li key={result.service} role="none">
              <a
                role="menuitem"
                href={result.url}
                target="_blank"
                rel="noopener noreferrer"
                onClick={() => {
                  onOpen?.(result);
                  setOpen(false);
                }}
              >
                {result.name}
                {' '}
                <small>{result.autoSubmit ? 'Runs' : 'Ready'}</small>
              </a>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};
`;
}
